### ISSUE TITLE
info.json can't be read by QMK

### ISSUE THREAD

**Issue by NeutroniumDev** [noroadsleft/kbf_qmk_converter#3]
I'm trying to import the info.json into qmk but it says it's not a qmk file. I think it might have something to do with layers and updated formatting in qmk. 

![image](https://user-images.githubusercontent.com/49597455/120576065-05587400-c3d7-11eb-8592-e6847a55230f.png)

**Comment by noroadsleft** [comment]
If you're trying to import the `info.json` file into QMK Configurator using the button on the right here:

![image](https://user-images.githubusercontent.com/18669334/120589350-8fabd280-c3ed-11eb-97ae-ac6ad198e392.png)

... that's not going to work. The purpose of `info.json` is QMK Configurator's API consumes its contents so it knows what the keyboard is supposed to look like. The interface in the image above is for importing *keymap* JSON files, which are the same file format, but a different file *structure*.

JSON as a file format is just data, and it's up to the designers/maintainers of the tooling that will use said data what the contents of the file should be.

If you're using my converter to attempt to add support for a new keyboard into QMK, you need to:

1. [Fork and clone the qmk/qmk_firmware repository](https://docs.qmk.fm/#/getting_started_github),
2. [Create a branch which will contain the source code for the keyboard](https://docs.qmk.fm/#/newbs_getting_started?id=set-up-your-environment)
3. [Open a Pull Request from the created branch to the `master` branch of the `qmk/qmk_firmware` repository](https://docs.qmk.fm/#/getting_started_github) (same link as Step 1)

If you're just trying to test the generated `info.json` file:

1. Go to the [QMK Configurator](https://config.qmk.fm/)
2. Hit `Ctrl`+`Shift`+`I`, in that order (Ctrl before Shift)
3. Upload your saved `info.json` file.

Either way, I'm sure I can help you figure out what needs doing, but I don't understand what task it is you're trying to accomplish. Let me know.

**Comment by noroadsleft** [comment]
No further response from OP. Closing, but pinning this issue in case anyone else gets confused here.
