### ISSUE TITLE
Problems with key heights and width smaller than 1 unit

### ISSUE THREAD

**Issue by federvieh** [noroadsleft/kbf_qmk_converter#6]
When importing [this json file](https://github.com/federvieh/qmk_firmware/blob/e203669c554b25fb5dcb7e70fe479b5a09be3401/keyboards/converter/lenovo_tp_usb/lenovo.json), the converter creates an output like this:
![image](https://user-images.githubusercontent.com/5159306/132997223-94bd0b57-39ca-41a5-a837-1f8c0d86d09d.png)

The reason is, that the rows of the keys start at 0.0, 0.75, 1.75, 2.75, 3.75, 4.75, and 5.5.

Due to the `Math.floor()` in [this line](https://github.com/noroadsleft/kbf_qmk_converter/blob/0824aa38aed26702c4fe9ad16173ce9c0d1b76d3/showOutput3.js#L1155) the lines starting at 0.0 and 0.75 are being merged.

The problem can be worked around by letting the rows in the input json file start at full integers (0, 1, 2, 3, 4, 5, and 6 in my case).

The remaining minor issue is then, that some keys in the first row are only 0.8 units wide. So after fixing input file according to above workaround, the output looks like this:
![image](https://user-images.githubusercontent.com/5159306/132997513-796e2fec-4167-4006-8d03-9931745ef764.png)

This I worked around, by manually fixing the output file.

So the whole thing works for me and I file this issue for future reference.

**Comment by noroadsleft** [comment]
Tested with your KBF JSON and it's a lot better now.

Minor aside: I wish all bug reports/issues around QMK were as detailed as yours. :heart:

**Comment by federvieh** [comment]
Wow, thanks for the fixing it so quickly. And thanks for all your work around QMK!
